export {
  default,
  Close,
  InfoIcon,
  ChatIcon,
  QuestionsIcon,
  PhoneIcon,
  BackIcon,
  TestResults,
  TracingIcon,
  CirclesBig,
  CirclesSmall,
  IcelandMap,
  OnboardingPhoneIcon,
  OnboardingCardIcon,
  OnboardingChatIcon,
} from './Icons';
